version: '3.9'
services:
  server:
    build: .
    ports:
      - '4000:4000'
    environment:
      DATABASE_URL: 'mysql://root:1234@mysql:3306/docker_test'

  mysql:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: '1234'
    restart: always
    ports:
      - '3306:3306'

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    container_name: docker-example-phpmyadmin
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: '1234'

volumes:
  db_data:
